version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - TEMPORAL_HOST=temporal:7233
      - PORT=8888
    command: flask run --host=0.0.0.0 --port=8888
